version: "3"
services:
  server:
    container_name: douban-openapi-server
    build: .
    ports:
      - "5000:5000"
    environment:
      - REQUEST_HEADERS_User_Agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      - REQUEST_HEADERS_Referer="https://movie.douban.com/"